apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: Trace ID
          matcherRegex: "trace_id"
          matcherType: label
          datasourceUid: tempo
          url: "$${__value.raw}"

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: elasticsearch
        tags: [{ key: "service.name", value: "Resource.service\\.name" }]
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: "service.name", value: "service" }]
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki

  - name: Elasticsearch
    uid: elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "dotnet-logs*"
    editable: true
    jsonData:
      timeField: "@timestamp"
      logMessageField: "Body"
      logLevelField: "SeverityText"
    correlations:
      - targetUID: tempo
        label: "View Trace in Tempo"
        description: "Open trace by TraceId"
        type: query
        config:
          field: TraceId
          target:
            query: "$${__value.raw}"
            queryType: traceql
